Rails.application.config.assets.precompile += %w( cms9/favicon-16.png )
Rails.application.config.assets.precompile += %w( cms9/favicon-32.png )
Rails.application.config.assets.precompile += %w( cms9/favicon-48.png )
Rails.application.config.assets.precompile += %w( cms9/favicon-128.png )
Rails.application.config.assets.precompile += %w( cms9/favicon-256.png )
Rails.application.config.assets.precompile += %w( cms9/favicon-512.png )
